# Generated by Django 5.0.1 on 2024-01-28 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plmapp', '0002_alter_invitation_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assembly',
            fields=[
                ('part_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='plmapp.part')),
                ('manufacturer', models.CharField(max_length=200, verbose_name='manufacturer')),
            ],
            options={
                'abstract': False,
            },
            bases=('plmapp.part',),
        ),
        migrations.CreateModel(
            name='BiosOs',
            fields=[
                ('part_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='plmapp.part')),
                ('size_in_mo', models.IntegerField(verbose_name='size in mo')),
            ],
            options={
                'abstract': False,
            },
            bases=('plmapp.part',),
        ),
        migrations.CreateModel(
            name='SinglePart',
            fields=[
                ('part_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='plmapp.part')),
                ('supplier', models.CharField(max_length=200, verbose_name='supplier')),
                ('tech_details', models.TextField(blank=True, verbose_name='tech details')),
            ],
            options={
                'abstract': False,
            },
            bases=('plmapp.part',),
        ),
        migrations.CreateModel(
            name='ReferenceDesignator',
            fields=[
                ('parentchildlinkextension_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='plmapp.parentchildlinkextension')),
                ('reference_designator', models.CharField(blank=True, max_length=200, verbose_name='reference designator')),
            ],
            options={
                'abstract': False,
            },
            bases=('plmapp.parentchildlinkextension',),
        ),
        migrations.CreateModel(
            name='CentralUnit',
            fields=[
                ('assembly_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='computer.assembly')),
                ('tech_characteristics', models.TextField(blank=True, verbose_name='tech characteristics')),
            ],
            options={
                'abstract': False,
            },
            bases=('computer.assembly',),
        ),
        migrations.CreateModel(
            name='ComputerSet',
            fields=[
                ('assembly_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='computer.assembly')),
                ('customer', models.CharField(max_length=200, verbose_name='customer')),
            ],
            options={
                'abstract': False,
            },
            bases=('computer.assembly',),
        ),
        migrations.CreateModel(
            name='OtherAssembly',
            fields=[
                ('assembly_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='computer.assembly')),
                ('tech_details', models.TextField(blank=True, verbose_name='tech details')),
            ],
            options={
                'abstract': False,
            },
            bases=('computer.assembly',),
        ),
        migrations.CreateModel(
            name='ElectronicPart',
            fields=[
                ('singlepart_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='computer.singlepart')),
            ],
            options={
                'abstract': False,
            },
            bases=('computer.singlepart',),
        ),
        migrations.CreateModel(
            name='HardDisk',
            fields=[
                ('singlepart_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='computer.singlepart')),
                ('capacity_in_go', models.PositiveIntegerField(verbose_name='capacity in go')),
            ],
            options={
                'abstract': False,
            },
            bases=('computer.singlepart',),
        ),
        migrations.CreateModel(
            name='KeyBoard',
            fields=[
                ('singlepart_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='computer.singlepart')),
                ('keymap', models.CharField(choices=[('qw', 'Qwerty'), ('az', 'Azerty')], max_length=20, verbose_name='keymap')),
            ],
            options={
                'abstract': False,
            },
            bases=('computer.singlepart',),
        ),
        migrations.CreateModel(
            name='MechanicalPart',
            fields=[
                ('singlepart_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='computer.singlepart')),
            ],
            options={
                'abstract': False,
            },
            bases=('computer.singlepart',),
        ),
        migrations.CreateModel(
            name='MotherBoard',
            fields=[
                ('singlepart_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='computer.singlepart')),
                ('motherboard_type', models.CharField(max_length=200, verbose_name='motherboard type')),
            ],
            options={
                'abstract': False,
            },
            bases=('computer.singlepart',),
        ),
        migrations.CreateModel(
            name='Mouse',
            fields=[
                ('singlepart_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='computer.singlepart')),
                ('number_of_buttons', models.PositiveSmallIntegerField(default=3, verbose_name='number of buttons')),
            ],
            options={
                'abstract': False,
            },
            bases=('computer.singlepart',),
        ),
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('singlepart_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='computer.singlepart')),
                ('size_in_mo', models.PositiveIntegerField(verbose_name='size in mo')),
            ],
            options={
                'abstract': False,
            },
            bases=('computer.singlepart',),
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('singlepart_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='computer.singlepart')),
                ('horizontal_resolution', models.IntegerField(verbose_name='horizontal resolution')),
                ('vertical_resolution', models.IntegerField(verbose_name='vertical resolution')),
            ],
            options={
                'abstract': False,
            },
            bases=('computer.singlepart',),
        ),
    ]
