# Generated by Django 5.0.1 on 2024-01-28 12:35

import django.contrib.auth.models
import django.core.files.storage
import django.db.models.deletion
import django.utils.timezone
import openPLM.plmapp.models.document
import openPLM.plmapp.models.lifecycle
import openPLM.plmapp.models.user
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PLMObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(db_index=True, help_text='Required. 50 characters or fewer. Letters, numbers , except #, ?, / and .. characters', max_length=50, verbose_name='reference')),
                ('type', models.CharField(max_length=50, verbose_name='type')),
                ('revision', models.CharField(max_length=50, verbose_name='revision')),
                ('reference_number', models.IntegerField(default=0)),
                ('name', models.CharField(blank=True, help_text='Name of the product', max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('ctime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date of creation')),
                ('mtime', models.DateTimeField(auto_now=True, verbose_name='date of last modification')),
                ('published', models.BooleanField(default=False, verbose_name='published')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owner', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'ordering': ['type', 'reference', 'revision'],
            },
        ),
        migrations.CreateModel(
            name='GroupInfo',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.group')),
                ('description', models.TextField(blank=True)),
                ('ctime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date of creation')),
                ('mtime', models.DateTimeField(auto_now=True, verbose_name='date of last modification')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owner', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
         migrations.CreateModel(
            name='State',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Lifecycle',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'standard'), (2, 'cancelled'), (3, 'ECR'), (4, 'template')], default=1)),
                ('official_state', models.ForeignKey('plmapp.State', on_delete=models.CASCADE)),
            ],
        ),
        migrations.CreateModel(
            name='ParentChildLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('quantity', models.FloatField(default=1)),
                ('unit', models.CharField(choices=[('Amounts', [('-', 'Each'), ('mol', 'mol')]), ('Lengths', [('mm', 'mm'), ('cm', 'cm'), ('dm', 'dm'), ('m', 'm'), ('km', 'km')]), ('Volumes', [('m3', 'm³'), ('mL', 'mL'), ('cL', 'cL'), ('dL', 'dL'), ('L', 'L')]), ('Masses', [('mg', 'mg'), ('cg', 'cg'), ('dg', 'dg'), ('g', 'g'), ('kg', 'kg')])], default='-', max_length=4)),
                ('order', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
        
        migrations.CreateModel(
            name='Document',
            fields=[
                ('plmobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='plmapp.plmobject')),
                ('template', models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tpl_instances', to='plmapp.document')),
            ],
            bases=('plmapp.plmobject',),
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('plmobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='plmapp.plmobject')),
            ],
            bases=('plmapp.plmobject', models.Model),
        ),
        migrations.CreateModel(
            name='GroupHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('Create', 'Create'), ('Delete', 'Delete'), ('Modify', 'Modify'), ('Revise', 'Revise'), ('Promote', 'Promote'), ('Demote', 'Demote'), ('Cancel', 'Cancel'), ('Publish', 'Publish'), ('Unpublish', 'Unpublish')], max_length=50)),
                ('details', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('plmobject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='plmobject',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_group', to='plmapp.groupinfo', verbose_name='group'),
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('Create', 'Create'), ('Delete', 'Delete'), ('Modify', 'Modify'), ('Revise', 'Revise'), ('Promote', 'Promote'), ('Demote', 'Demote'), ('Cancel', 'Cancel'), ('Publish', 'Publish'), ('Unpublish', 'Unpublish')], max_length=50)),
                ('details', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('plmobject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plmapp.plmobject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('state', models.CharField(choices=[('p', 'Pending'), ('a', 'Accepted'), ('r', 'Refused')], default='p', max_length=10)),
                ('ctime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date of creation')),
                ('validation_time', models.DateTimeField(null=True, verbose_name='date of validation')),
                ('guest_asked', models.BooleanField(verbose_name='True if guest created the invitation')),
                ('token', models.CharField(default='4027504337099281505020594515882494415713829401175016709978650141581200964834757918911783525609652412697096370759095085574962070930243668192649444241026882', max_length=155, primary_key=True, serialize=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plmapp.groupinfo')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_inv_guest', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_inv_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='plmobject',
            name='lifecycle',
            field=models.ForeignKey(default=openPLM.plmapp.models.lifecycle.get_default_lifecycle, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='plmapp.lifecycle', verbose_name='lifecycle'),
        ),
        migrations.CreateModel(
            name='ParentChildLinkExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_child_name', models.CharField(editable=False, max_length=100)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_link', to='plmapp.parentchildlink')),
            ],
        ),
        migrations.CreateModel(
            name='PrivateFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=200)),
                ('file', models.FileField(storage=openPLM.plmapp.models.document.DocumentStorage(location='/var/openPLM/docs/'), upload_to='.')),
                ('size', models.PositiveIntegerField()),
                ('ctime', models.DateTimeField(default=django.utils.timezone.now)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='plmobject',
            name='state',
            field=models.ForeignKey(default=openPLM.plmapp.models.lifecycle.get_default_state, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='plmapp.state', verbose_name='state'),
        ),
        migrations.AddField(
            model_name='lifecycle',
            name='official_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plmapp.state'),
        ),
        migrations.CreateModel(
            name='StateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date of promotion')),
                ('end_time', models.DateTimeField(null=True)),
                ('state_category', models.PositiveSmallIntegerField(choices=[(0, 'draft'), (1, 'proposed'), (2, 'official'), (3, 'deprecated'), (4, 'cancelled')])),
                ('lifecycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plmapp.lifecycle')),
                ('plmobject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plmapp.plmobject')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plmapp.state')),
            ],
        ),
        migrations.CreateModel(
            name='UserHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('Create', 'Create'), ('Delete', 'Delete'), ('Modify', 'Modify'), ('Revise', 'Revise'), ('Promote', 'Promote'), ('Demote', 'Demote'), ('Cancel', 'Cancel'), ('Publish', 'Publish'), ('Unpublish', 'Unpublish')], max_length=50)),
                ('details', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('plmobject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_administrator', models.BooleanField(blank=True, default=False)),
                ('is_contributor', models.BooleanField(blank=True, default=False)),
                ('can_publish', models.BooleanField(blank=True, default=False)),
                ('restricted', models.BooleanField(blank=True, default=False)),
                ('language', models.CharField(choices=[('fr', 'Français'), ('en', 'English'), ('es', 'Español'), ('ja', '日本語'), ('ru', 'Русский'), ('zh-hans', '中文')], default='en', max_length=10)),
                ('avatar', models.ImageField(blank=True, null=True, storage=openPLM.plmapp.models.user.AvatarStorage(), upload_to='avatars')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DelegationLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('role', models.CharField(choices=[('owner', 'owner'), ('notified', 'notified'), ('sponsor', 'sponsor'), ('sign_1st_level', 'sign_1st_level'), ('sign_2nd_level', 'sign_2nd_level'), ('sign_3rd_level', 'sign_3rd_level'), ('sign_4th_level', 'sign_4th_level'), ('sign_5th_level', 'sign_5th_level'), ('sign_6th_level', 'sign_6th_level'), ('sign_7th_level', 'sign_7th_level'), ('sign_8th_level', 'sign_8th_level'), ('sign_9th_level', 'sign_9th_level'), ('sign_10th_level', 'sign_10th_level'), ('reader', 'reader')], db_index=True, max_length=30)),
                ('delegatee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_delegatee', to=settings.AUTH_USER_MODEL)),
                ('delegator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_delegator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('delegator', 'delegatee', 'role', 'end_time')},
            },
        ),
        migrations.CreateModel(
            name='DocumentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=200)),
                ('file', models.FileField(storage=openPLM.plmapp.models.document.DocumentStorage(location='/var/openPLM/docs/'), upload_to='.')),
                ('size', models.PositiveIntegerField()),
                ('thumbnail', models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/thumbnails/', location='/var/django/openPLM/trunk/openPLM/media/thumbnails/'), upload_to='.')),
                ('locked', models.BooleanField(default=False)),
                ('deprecated', models.BooleanField(default=False)),
                ('ctime', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('revision', models.IntegerField(default=1)),
                ('last_revision', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='older_files', to='plmapp.documentfile')),
                ('locker', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('previous_revision', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_revision', to='plmapp.documentfile')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plmapp.document')),
            ],
        ),
        migrations.AddField(
            model_name='parentchildlink',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_child', to='plmapp.part'),
        ),
        migrations.AddField(
            model_name='parentchildlink',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_parent', to='plmapp.part'),
        ),
        migrations.CreateModel(
            name='AlternatePartSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('parts', models.ManyToManyField(related_name='%(class)ss', to='plmapp.part')),
            ],
        ),
        migrations.CreateModel(
            name='PLMObjectUserLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('role', models.CharField(choices=[('owner', 'owner'), ('notified', 'notified'), ('sponsor', 'sponsor'), ('sign_1st_level', 'sign_1st_level'), ('sign_2nd_level', 'sign_2nd_level'), ('sign_3rd_level', 'sign_3rd_level'), ('sign_4th_level', 'sign_4th_level'), ('sign_5th_level', 'sign_5th_level'), ('sign_6th_level', 'sign_6th_level'), ('sign_7th_level', 'sign_7th_level'), ('sign_8th_level', 'sign_8th_level'), ('sign_9th_level', 'sign_9th_level'), ('sign_10th_level', 'sign_10th_level'), ('reader', 'reader')], db_index=True, max_length=30)),
                ('plmobject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='plmapp.plmobject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user', 'role', 'plmobject__type', 'plmobject__reference', 'plmobject__revision'],
                'unique_together': {('plmobject', 'user', 'role', 'end_time')},
            },
        ),
        migrations.CreateModel(
            name='RevisionLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('new', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_new', to='plmapp.plmobject')),
                ('old', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_old', to='plmapp.plmobject')),
            ],
            options={
                'unique_together': {('old', 'new', 'end_time')},
            },
        ),
        migrations.CreateModel(
            name='PromotionApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('plmobject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='plmapp.plmobject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to=settings.AUTH_USER_MODEL)),
                ('current_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='plmapp.state')),
                ('next_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='plmapp.state')),
            ],
            options={
                'unique_together': {('plmobject', 'user', 'current_state', 'next_state', 'end_time')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='plmobject',
            unique_together={('reference', 'type', 'revision')},
        ),
        migrations.CreateModel(
            name='LifecycleStates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveSmallIntegerField()),
                ('lifecycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plmapp.lifecycle')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plmapp.state')),
            ],
            options={
                'unique_together': {('lifecycle', 'state')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='parentchildlink',
            unique_together={('parent', 'child', 'end_time')},
        ),
        migrations.CreateModel(
            name='DocumentPartLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_document', to='plmapp.document')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_part', to='plmapp.part')),
            ],
            options={
                'unique_together': {('document', 'part', 'end_time')},
            },
        ),
    ]
