# Generated by Django 5.0.1 on 2024-01-28 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plmapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='token',
            field=models.CharField(default='3625561440224694784660506430101615449853822177380737660240312088372583881037467901692545633418743122490344445277101260865806575251016327546389346906522425', max_length=155, primary_key=True, serialize=False),
        ),
    ]
