# Generated by Django 5.0.1 on 2024-01-28 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plmapp', '0002_alter_invitation_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='plmapp.document')),
            ],
            options={
                'abstract': False,
            },
            bases=('plmapp.document',),
        ),
        migrations.CreateModel(
            name='Drawing',
            fields=[
                ('design_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cad.design')),
                ('nb_pages', models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of pages')),
                ('format', models.CharField(choices=[('A6', 'A6'), ('A5', 'A5'), ('A4', 'A4'), ('A10', 'A10'), ('A3', 'A3'), ('A9', 'A9'), ('A2', 'A2'), ('A8', 'A8'), ('A1', 'A1'), ('A7', 'A7'), ('A0', 'A0'), ('Other', 'Other')], default='A4', max_length=10, verbose_name='format')),
            ],
            options={
                'abstract': False,
            },
            bases=('cad.design',),
        ),
        migrations.CreateModel(
            name='FMEA',
            fields=[
                ('design_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cad.design')),
            ],
            options={
                'abstract': False,
            },
            bases=('cad.design',),
        ),
        migrations.CreateModel(
            name='FreeCAD',
            fields=[
                ('design_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cad.design')),
            ],
            options={
                'abstract': False,
            },
            bases=('cad.design',),
        ),
        migrations.CreateModel(
            name='Patent',
            fields=[
                ('design_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cad.design')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='expiration date')),
                ('inventor', models.CharField(blank=True, max_length=50, verbose_name='inventor')),
            ],
            options={
                'abstract': False,
            },
            bases=('cad.design',),
        ),
        migrations.CreateModel(
            name='Sketch',
            fields=[
                ('design_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cad.design')),
            ],
            options={
                'abstract': False,
            },
            bases=('cad.design',),
        ),
        migrations.CreateModel(
            name='CustomerDrawing',
            fields=[
                ('drawing_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cad.drawing')),
                ('customer', models.CharField(blank=True, max_length=50, verbose_name='customer')),
            ],
            options={
                'abstract': False,
            },
            bases=('cad.drawing',),
        ),
        migrations.CreateModel(
            name='SupplierDrawing',
            fields=[
                ('drawing_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cad.drawing')),
                ('supplier', models.CharField(blank=True, max_length=50, verbose_name='supplier')),
            ],
            options={
                'abstract': False,
            },
            bases=('cad.drawing',),
        ),
    ]
